let LESSON_SLIDE_TYPES
export default LESSON_SLIDE_TYPES = {
  FULL_PAGE_TEXT: 'FULL_PAGE_TEXT'
  , HALF_HALF: 'HALF_HALF'
  , FULL_PAGE_CODE_EDITOR: 'FULL_PAGE_CODE_EDITOR'
  , TITLE: 'TITLE'
  , FULL_PAGE_CODE_EXAMPLE: 'FULL_PAGE_CODE_EXAMPLE'
}
