let LESSON_SLIDE_TYPES
export default LESSON_SLIDE_TYPES = { // must match kiwi-node version
  FULL_PAGE_TEXT: 'FULL_PAGE_TEXT'
  , FULL_PAGE_CODE_EDITOR: 'FULL_PAGE_CODE_EDITOR'
  , TITLE: 'TITLE'
  , FULL_PAGE_CODE_EXAMPLE: 'FULL_PAGE_CODE_EXAMPLE'
  , MULTIPLE_CHOICE: 'MULTIPLE_CHOICE'
}
