export const CODE_CONCEPTS = {
  LOOP: 'LOOP'
  , FOR_LOOP: 'FOR_LOOP'
  , WHILE_LOOP: 'WHILE_LOOP'
  , CONDITIONAL: 'CONDITIONAL'
  , IF: 'IF'
  , ELIF: 'ELIF'
  , ELSE: 'ELSE'
}

export const COMPARISON_TYPES = {
  NEVER: 'NEVER'
  , AT_LEAST_ONCE: 'AT_LEAST_ONCE'
  , ONLY_ONCE: 'ONLY_ONCE'
  , CUSTOM: 'CUSTOM'
  , AT_LEAST: 'AT_LEAST'
  , ONLY: 'ONLY'
  , NO_MORE_THAN: 'NO_MORE_THAN'
}